export const environment = {
  API_KEY: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxYTViYTdjMjc5YWI5ZjgwYTY5NjkzNjhiODI5N2VjYyIsInN1YiI6IjY0Zjc4MjcwMmNkZTk4MDEzYTk2ZDdhZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.A63W2jfXTtMD5uK-WpGx8lOn-thzsDPoENQbSnDHcxQ"
};
